
    //Lets define a unique label for this build.
    def label = "buildpod.${env.JOB_NAME}.${env.BUILD_NUMBER}".replace('-', '_').replace('/', '_')

    //Lets create a new pod template with jnlp and maven containers, that uses that label.
    def myimagenamespa = 'myappspa'
    def myimagenametodo = 'myapptodo'
    
    podTemplate(label: label, containers: [
            containerTemplate(name: 'docker', image: 'docker', ttyEnabled: true, privileged: true, command: 'cat'),     
            containerTemplate(name: 'helm', image: 'lachlanevenson/k8s-helm:v2.12.1', ttyEnabled: true, command: 'cat'),
            containerTemplate(name: 'kubectl', image: 'lachlanevenson/k8s-kubectl:v1.11.0', ttyEnabled: true, command: 'cat'),
            containerTemplate(name: 'jnlp', image: 'jenkinsci/jnlp-slave:alpine', command: '/usr/local/bin/jenkins-slave', args: '-url http://myjenkins-jenkins:8080 ${computer.jnlpmac} ${computer.name}', ttyEnabled: false)],           
            volumes: [
                hostPathVolume(mountPath: "/var/run/docker.sock", hostPath: "/var/run/docker.sock")
                ]) {

        //Lets use pod template (refernce by label)
        node(label){
            withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId: params.acr,
                    usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]){

                def built_img = ''
    
                stage('Checkout git repo') {
                    git url: params.giturl, branch: params.gitbranch            
                }
                stage('Build docker images') {
                        container(name: 'docker') {
                          sh "docker login -p "+env.PASSWORD+" -u "+env.USERNAME+" " + params.acr

                          sh "docker build -t "+params.acr+"/"+myimagenamespa+":${env.BUILD_NUMBER} ./module01/src/myappspa"
                          sh "docker tag "+params.acr+"/"+myimagenamespa+":${env.BUILD_NUMBER} "+params.acr+"/"+myimagenamespa+":latest"
                          sh "docker push "+params.acr+"/"+myimagenamespa+":latest"
                          sh "docker push "+params.acr+"/"+myimagenamespa+":${env.BUILD_NUMBER}"

                          sh "docker build -t "+params.acr+"/"+myimagenametodo+":${env.BUILD_NUMBER} ./module01/src/myapptodo"
                          sh "docker tag "+params.acr+"/"+myimagenametodo+":${env.BUILD_NUMBER} "+params.acr+"/"+myimagenametodo+":latest"
                          sh "docker push "+params.acr+"/"+myimagenametodo+":latest"
                          sh "docker push "+params.acr+"/"+myimagenametodo+":${env.BUILD_NUMBER}"
                        }
                }
                stage('Deploy docker image') {
                    container(name: 'kubectl') {
                        sh "kubectl get nodes"
                    }
                    dir('module05/helm'){
                        container(name: 'helm') {
                            def overrides = "appspa.image.repository='"+params.acr+"/"+myimagenamespa+"',appspa.image.tag=${env.BUILD_NUMBER},apptodo.image.repository='"+params.acr+"/"+myimagenametodo+"',apptodo.image.tag=${env.BUILD_NUMBER},apphost='"+params.ingressdns+"'"
                            def releaseName = params.releasename
                            def namespace = "'"+params.appns+"'"
                            def chart_dir = "myapp"
                            
                            sh "helm version"
                            sh "helm lint ${chart_dir}"
                            sh "helm upgrade --install --wait ${releaseName} ${chart_dir} --set-string ${overrides} --namespace=${namespace}"
                        }
                    }
                }
            }
        }
    }